spring:
  application:
    name: document-intelligence-platform
  config:
    import:
      - optional:classpath:application-local.yml
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  docker:
    compose:
      skip:
        in-tests: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o
    vectorstore:
      pgvector:
        initialize-schema: true

app:
  chunking:
    size: 500
    overlap: 100

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
