spring:
  application:
    name: document-intelligence-platform
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  
  datasource:
    url: jdbc:postgresql://localhost:5433/mydatabase
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  docker:
    compose:
      skip:
        in-tests: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY: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}
      chat:
        options:
          model: gpt-4o
    vectorstore:
      pgvector:
        initialize-schema: true

app:
  chunking:
    size: 500
    overlap: 100
